/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.lexer;

import java.io.*;
import java.util.*;
import minipython.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TTab(text, line, pos); }
    Token new1(int line, int pos) { return new TPlus(line, pos); }
    Token new2(int line, int pos) { return new TMinus(line, pos); }
    Token new3(int line, int pos) { return new TMult(line, pos); }
    Token new4(int line, int pos) { return new TDiv(line, pos); }
    Token new5(int line, int pos) { return new TEq(line, pos); }
    Token new6(int line, int pos) { return new TDeq(line, pos); }
    Token new7(int line, int pos) { return new TMinusEq(line, pos); }
    Token new8(int line, int pos) { return new TDivEq(line, pos); }
    Token new9(int line, int pos) { return new TNotEqual(line, pos); }
    Token new10(int line, int pos) { return new TDef(line, pos); }
    Token new11(int line, int pos) { return new TLPar(line, pos); }
    Token new12(int line, int pos) { return new TRPar(line, pos); }
    Token new13(int line, int pos) { return new TLBr(line, pos); }
    Token new14(int line, int pos) { return new TRBr(line, pos); }
    Token new15(int line, int pos) { return new TIf(line, pos); }
    Token new16(int line, int pos) { return new TWhile(line, pos); }
    Token new17(int line, int pos) { return new TFor(line, pos); }
    Token new18(int line, int pos) { return new TPrint(line, pos); }
    Token new19(int line, int pos) { return new TReturn(line, pos); }
    Token new20(int line, int pos) { return new TComma(line, pos); }
    Token new21(int line, int pos) { return new TIn(line, pos); }
    Token new22(int line, int pos) { return new TLess(line, pos); }
    Token new23(int line, int pos) { return new TGreat(line, pos); }
    Token new24(int line, int pos) { return new TTrue(line, pos); }
    Token new25(int line, int pos) { return new TSemi(line, pos); }
    Token new26(int line, int pos) { return new TFalse(line, pos); }
    Token new27(String text, int line, int pos) { return new TQuote(text, line, pos); }
    Token new28(String text, int line, int pos) { return new TSquote(text, line, pos); }
    Token new29(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new30(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new31(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new33(String text, int line, int pos) { return new TString1(text, line, pos); }
    Token new34(String text, int line, int pos) { return new TString2(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {97, 99, 24}, {100, 100, 25}, {101, 101, 24}, {102, 102, 26}, {103, 104, 24}, {105, 105, 27}, {106, 111, 24}, {112, 112, 28}, {113, 113, 24}, {114, 114, 29}, {115, 115, 24}, {116, 116, 30}, {117, 118, 24}, {119, 119, 31}, {120, 122, 24}, },
            {},
            {},
            {},
            {},
            {{61, 61, 32}, },
            {{32, 32, 33}, {65, 90, 34}, {97, 122, 35}, },
            {{0, 9, 36}, {10, 10, 37}, {11, 12, 36}, {13, 13, 38}, {14, 127, 36}, },
            {{32, 32, 39}, {65, 90, 40}, {97, 122, 41}, },
            {},
            {},
            {},
            {},
            {},
            {{61, 61, 42}, },
            {{61, 61, 43}, },
            {{48, 57, 16}, },
            {},
            {},
            {{61, 61, 44}, },
            {},
            {{48, 57, 45}, {65, 90, 46}, {97, 122, 47}, },
            {},
            {},
            {{48, 122, -23}, },
            {{48, 90, -23}, {97, 100, 47}, {101, 101, 48}, {102, 122, 47}, },
            {{48, 90, -23}, {97, 97, 49}, {98, 110, 47}, {111, 111, 50}, {112, 122, 47}, },
            {{48, 90, -23}, {97, 101, 47}, {102, 102, 51}, {103, 109, 47}, {110, 110, 52}, {111, 122, 47}, },
            {{48, 90, -23}, {97, 113, 47}, {114, 114, 53}, {115, 122, 47}, },
            {{48, 100, -27}, {101, 101, 54}, {102, 122, 47}, },
            {{48, 113, -30}, {114, 114, 55}, {115, 122, 47}, },
            {{48, 90, -23}, {97, 103, 47}, {104, 104, 56}, {105, 122, 47}, },
            {},
            {{32, 32, 33}, {34, 34, 57}, {65, 122, -8}, },
            {{32, 122, -35}, },
            {{32, 122, -35}, },
            {{0, 127, -9}, },
            {},
            {{10, 10, 58}, },
            {{32, 32, 39}, {39, 39, 59}, {65, 122, -10}, },
            {{32, 122, -41}, },
            {{32, 122, -41}, },
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 101, -29}, {102, 102, 60}, {103, 122, 47}, },
            {{48, 90, -23}, {97, 107, 47}, {108, 108, 61}, {109, 122, 47}, },
            {{48, 113, -30}, {114, 114, 62}, {115, 122, 47}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 90, -23}, {97, 104, 47}, {105, 105, 63}, {106, 122, 47}, },
            {{48, 90, -23}, {97, 115, 47}, {116, 116, 64}, {117, 122, 47}, },
            {{48, 90, -23}, {97, 116, 47}, {117, 117, 65}, {118, 122, 47}, },
            {{48, 104, -55}, {105, 105, 66}, {106, 122, 47}, },
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 90, -23}, {97, 114, 47}, {115, 115, 67}, {116, 122, 47}, },
            {{48, 122, -23}, },
            {{48, 90, -23}, {97, 109, 47}, {110, 110, 68}, {111, 122, 47}, },
            {{48, 116, -57}, {117, 117, 69}, {118, 122, 47}, },
            {{48, 100, -27}, {101, 101, 70}, {102, 122, 47}, },
            {{48, 107, -51}, {108, 108, 71}, {109, 122, 47}, },
            {{48, 100, -27}, {101, 101, 72}, {102, 122, 47}, },
            {{48, 115, -56}, {116, 116, 73}, {117, 122, 47}, },
            {{48, 113, -30}, {114, 114, 74}, {115, 122, 47}, },
            {{48, 122, -23}, },
            {{48, 100, -27}, {101, 101, 75}, {102, 122, 47}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 109, -65}, {110, 110, 76}, {111, 122, 47}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 0, 29, 29, 29, -1, 27, -1, 28, 11, 12, 3, 1, 20, 2, 4, 31, 25, 22, 5, 23, 32, 13, 14, 32, 32, 32, 32, 32, 32, 32, 32, 9, -1, -1, -1, -1, 30, 30, -1, -1, -1, 7, 8, 6, 32, 32, 32, 32, 32, 32, 15, 21, 32, 32, 32, 32, 33, 30, 34, 10, 32, 17, 32, 32, 32, 32, 32, 32, 32, 24, 32, 26, 18, 32, 16, 19, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
