/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArgArgument extends PArgument
{
    private TIdentifier _identifier_;
    private PEqValue _eqValue_;
    private final LinkedList _argument2_ = new TypedLinkedList(new Argument2_Cast());

    public AArgArgument()
    {
    }

    public AArgArgument(
        TIdentifier _identifier_,
        PEqValue _eqValue_,
        List _argument2_)
    {
        setIdentifier(_identifier_);

        setEqValue(_eqValue_);

        {
            this._argument2_.clear();
            this._argument2_.addAll(_argument2_);
        }

    }
    public Object clone()
    {
        return new AArgArgument(
            (TIdentifier) cloneNode(_identifier_),
            (PEqValue) cloneNode(_eqValue_),
            cloneList(_argument2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgArgument(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PEqValue getEqValue()
    {
        return _eqValue_;
    }

    public void setEqValue(PEqValue node)
    {
        if(_eqValue_ != null)
        {
            _eqValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eqValue_ = node;
    }

    public LinkedList getArgument2()
    {
        return _argument2_;
    }

    public void setArgument2(List list)
    {
        _argument2_.clear();
        _argument2_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_eqValue_)
            + toString(_argument2_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_eqValue_ == child)
        {
            _eqValue_ = null;
            return;
        }

        if(_argument2_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_eqValue_ == oldChild)
        {
            setEqValue((PEqValue) newChild);
            return;
        }

        for(ListIterator i = _argument2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Argument2_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArgument2 node = (PArgument2) o;

            if((node.parent() != null) &&
                (node.parent() != AArgArgument.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArgArgument.this))
            {
                node.parent(AArgArgument.this);
            }

            return node;
        }
    }
}
