/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArg2Argument2 extends PArgument2
{
    private TComma _comma_;
    private TIdentifier _identifier_;
    private PEqValue _eqValue_;

    public AArg2Argument2()
    {
    }

    public AArg2Argument2(
        TComma _comma_,
        TIdentifier _identifier_,
        PEqValue _eqValue_)
    {
        setComma(_comma_);

        setIdentifier(_identifier_);

        setEqValue(_eqValue_);

    }
    public Object clone()
    {
        return new AArg2Argument2(
            (TComma) cloneNode(_comma_),
            (TIdentifier) cloneNode(_identifier_),
            (PEqValue) cloneNode(_eqValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArg2Argument2(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PEqValue getEqValue()
    {
        return _eqValue_;
    }

    public void setEqValue(PEqValue node)
    {
        if(_eqValue_ != null)
        {
            _eqValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eqValue_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_identifier_)
            + toString(_eqValue_);
    }

    void removeChild(Node child)
    {
        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_eqValue_ == child)
        {
            _eqValue_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_eqValue_ == oldChild)
        {
            setEqValue((PEqValue) newChild);
            return;
        }

    }
}
