/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ABrSomething extends PSomething
{
    private TLBr _lBr_;
    private PExpression _expression_;
    private final LinkedList _comExpr_ = new TypedLinkedList(new ComExpr_Cast());
    private TRBr _rBr_;

    public ABrSomething()
    {
    }

    public ABrSomething(
        TLBr _lBr_,
        PExpression _expression_,
        List _comExpr_,
        TRBr _rBr_)
    {
        setLBr(_lBr_);

        setExpression(_expression_);

        {
            this._comExpr_.clear();
            this._comExpr_.addAll(_comExpr_);
        }

        setRBr(_rBr_);

    }
    public Object clone()
    {
        return new ABrSomething(
            (TLBr) cloneNode(_lBr_),
            (PExpression) cloneNode(_expression_),
            cloneList(_comExpr_),
            (TRBr) cloneNode(_rBr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABrSomething(this);
    }

    public TLBr getLBr()
    {
        return _lBr_;
    }

    public void setLBr(TLBr node)
    {
        if(_lBr_ != null)
        {
            _lBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBr_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getComExpr()
    {
        return _comExpr_;
    }

    public void setComExpr(List list)
    {
        _comExpr_.clear();
        _comExpr_.addAll(list);
    }

    public TRBr getRBr()
    {
        return _rBr_;
    }

    public void setRBr(TRBr node)
    {
        if(_rBr_ != null)
        {
            _rBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBr_)
            + toString(_expression_)
            + toString(_comExpr_)
            + toString(_rBr_);
    }

    void removeChild(Node child)
    {
        if(_lBr_ == child)
        {
            _lBr_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_comExpr_.remove(child))
        {
            return;
        }

        if(_rBr_ == child)
        {
            _rBr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBr_ == oldChild)
        {
            setLBr((TLBr) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _comExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBr_ == oldChild)
        {
            setRBr((TRBr) newChild);
            return;
        }

    }

    private class ComExpr_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PComExpr node = (PComExpr) o;

            if((node.parent() != null) &&
                (node.parent() != ABrSomething.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABrSomething.this))
            {
                node.parent(ABrSomething.this);
            }

            return node;
        }
    }
}
