/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AGoal extends PGoal
{
    private final LinkedList _program_ = new TypedLinkedList(new Program_Cast());

    public AGoal()
    {
    }

    public AGoal(
        List _program_)
    {
        {
            this._program_.clear();
            this._program_.addAll(_program_);
        }

    }
    public Object clone()
    {
        return new AGoal(
            cloneList(_program_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGoal(this);
    }

    public LinkedList getProgram()
    {
        return _program_;
    }

    public void setProgram(List list)
    {
        _program_.clear();
        _program_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_program_);
    }

    void removeChild(Node child)
    {
        if(_program_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _program_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Program_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PProgram node = (PProgram) o;

            if((node.parent() != null) &&
                (node.parent() != AGoal.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AGoal.this))
            {
                node.parent(AGoal.this);
            }

            return node;
        }
    }
}
