/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANoteqcComparison extends PComparison
{
    private PExpression _lpar_;
    private TNotEqual _notEqual_;
    private PExpression _rpar_;

    public ANoteqcComparison()
    {
    }

    public ANoteqcComparison(
        PExpression _lpar_,
        TNotEqual _notEqual_,
        PExpression _rpar_)
    {
        setLpar(_lpar_);

        setNotEqual(_notEqual_);

        setRpar(_rpar_);

    }
    public Object clone()
    {
        return new ANoteqcComparison(
            (PExpression) cloneNode(_lpar_),
            (TNotEqual) cloneNode(_notEqual_),
            (PExpression) cloneNode(_rpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoteqcComparison(this);
    }

    public PExpression getLpar()
    {
        return _lpar_;
    }

    public void setLpar(PExpression node)
    {
        if(_lpar_ != null)
        {
            _lpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lpar_ = node;
    }

    public TNotEqual getNotEqual()
    {
        return _notEqual_;
    }

    public void setNotEqual(TNotEqual node)
    {
        if(_notEqual_ != null)
        {
            _notEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _notEqual_ = node;
    }

    public PExpression getRpar()
    {
        return _rpar_;
    }

    public void setRpar(PExpression node)
    {
        if(_rpar_ != null)
        {
            _rpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rpar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lpar_)
            + toString(_notEqual_)
            + toString(_rpar_);
    }

    void removeChild(Node child)
    {
        if(_lpar_ == child)
        {
            _lpar_ = null;
            return;
        }

        if(_notEqual_ == child)
        {
            _notEqual_ = null;
            return;
        }

        if(_rpar_ == child)
        {
            _rpar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lpar_ == oldChild)
        {
            setLpar((PExpression) newChild);
            return;
        }

        if(_notEqual_ == oldChild)
        {
            setNotEqual((TNotEqual) newChild);
            return;
        }

        if(_rpar_ == oldChild)
        {
            setRpar((PExpression) newChild);
            return;
        }

    }
}
