/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APrintStatement extends PStatement
{
    private final LinkedList _tab_ = new TypedLinkedList(new Tab_Cast());
    private TPrint _print_;
    private PExpression _expression_;
    private final LinkedList _comExpr_ = new TypedLinkedList(new ComExpr_Cast());

    public APrintStatement()
    {
    }

    public APrintStatement(
        List _tab_,
        TPrint _print_,
        PExpression _expression_,
        List _comExpr_)
    {
        {
            this._tab_.clear();
            this._tab_.addAll(_tab_);
        }

        setPrint(_print_);

        setExpression(_expression_);

        {
            this._comExpr_.clear();
            this._comExpr_.addAll(_comExpr_);
        }

    }
    public Object clone()
    {
        return new APrintStatement(
            cloneList(_tab_),
            (TPrint) cloneNode(_print_),
            (PExpression) cloneNode(_expression_),
            cloneList(_comExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrintStatement(this);
    }

    public LinkedList getTab()
    {
        return _tab_;
    }

    public void setTab(List list)
    {
        _tab_.clear();
        _tab_.addAll(list);
    }

    public TPrint getPrint()
    {
        return _print_;
    }

    public void setPrint(TPrint node)
    {
        if(_print_ != null)
        {
            _print_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _print_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getComExpr()
    {
        return _comExpr_;
    }

    public void setComExpr(List list)
    {
        _comExpr_.clear();
        _comExpr_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_tab_)
            + toString(_print_)
            + toString(_expression_)
            + toString(_comExpr_);
    }

    void removeChild(Node child)
    {
        if(_tab_.remove(child))
        {
            return;
        }

        if(_print_ == child)
        {
            _print_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_comExpr_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _tab_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_print_ == oldChild)
        {
            setPrint((TPrint) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _comExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Tab_Cast implements Cast
    {
        public Object cast(Object o)
        {
            TTab node = (TTab) o;

            if((node.parent() != null) &&
                (node.parent() != APrintStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != APrintStatement.this))
            {
                node.parent(APrintStatement.this);
            }

            return node;
        }
    }

    private class ComExpr_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PComExpr node = (PComExpr) o;

            if((node.parent() != null) &&
                (node.parent() != APrintStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != APrintStatement.this))
            {
                node.parent(APrintStatement.this);
            }

            return node;
        }
    }
}
